[variables]
NIXPACKS_METADATA = 'python,django,nginx'
PIP_DEFAULT_TIMEOUT = '101'
PIP_DISABLE_PIP_VERSION_CHECK = '1'
PIP_NO_CACHE_DIR = '1'
PYTHONDONTWRITEBYTECODE = '1'
PYTHONFAULTHANDLER = '1'
PYTHONHASHSEED = 'random'
PYTHONUNBUFFERED = '1'
[phases.install]
dependsOn = ['setup']
cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt', 'mkdir -p /var/log/nginx']
cacheDirectories = ['/root/.cache/pip']
paths = ['/opt/venv/bin']

[phases.setup]
nixPkgs = [
'python3',
'gcc',
'gettext',
'nginx'
]
nixLibs = [
'zlib',
'stdenv.cc.cc.lib',
]
nixOverlays = []
nixpkgsArchive = 'bf446f08bff6814b569265bef8374cfdd3d8f0e0'

[phases.start]
cmd = '''
gunicorn toothease.wsgi:application --bind 0.0.0.0:8000
'''
